FROM nginx:stable-perl
COPY nginx.conf /etc/nginx/nginx.conf

COPY ./certs/intCA.pem /etc/ssl/certs/intCA.pem
COPY ./certs/rootCA.pem /etc/ssl/certs/rootCA.pem

COPY ./certs/testkey.pem /etc/ssl/testkey.pem
COPY ./certs/testcert.pem /etc/ssl/testcert.pem